package com.jobportal.utility;

import java.time.Year;

public class Data {
	public static String getMessageBody(String otp, String name) {

		return "<!DOCTYPE html>\n" + "<html lang=\"en\">\n" + "<head>\n" + "    <meta charset=\"UTF-8\">\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
				+ "    <title>Password Reset - JobPortal</title>\n" + "    <style>\n" + "        body {\n"
				+ "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n" + "            margin: 0;\n"
				+ "            padding: 0;\n" + "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
				+ "            min-height: 100vh;\n" + "        }\n"
				+ "        .container {\n" + "            max-width: 500px;\n" + "            margin: 20px auto;\n"
				+ "            background: #ffffff;\n" + "            border-radius: 16px;\n"
				+ "            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);\n" + "            overflow: hidden;\n"
				+ "        }\n"
				+ "        .header {\n" + "            background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);\n"
				+ "            color: #ffffff;\n" + "            padding: 30px 20px;\n" + "            text-align: center;\n"
				+ "            position: relative;\n" + "        }\n"
				+ "        .header::before {\n" + "            content: '🔐';\n" + "            font-size: 48px;\n"
				+ "            display: block;\n" + "            margin-bottom: 10px;\n" + "        }\n"
				+ "        .header h1 {\n" + "            margin: 0;\n" + "            font-size: 28px;\n"
				+ "            font-weight: 600;\n" + "        }\n"
				+ "        .body {\n" + "            padding: 40px 30px;\n" + "            color: #333333;\n"
				+ "            text-align: center;\n" + "            line-height: 1.6;\n" + "        }\n"
				+ "        .greeting {\n" + "            font-size: 18px;\n" + "            margin-bottom: 20px;\n"
				+ "            color: #555;\n" + "        }\n"
				+ "        .message {\n" + "            font-size: 16px;\n" + "            margin-bottom: 30px;\n"
				+ "            color: #666;\n" + "        }\n"
				+ "        .otp-container {\n" + "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
				+ "            border-radius: 12px;\n" + "            padding: 25px;\n" + "            margin: 30px 0;\n"
				+ "            box-shadow: 0 8px 16px rgba(102, 126, 234, 0.3);\n" + "        }\n"
				+ "        .otp-label {\n" + "            color: #ffffff;\n" + "            font-size: 14px;\n"
				+ "            margin-bottom: 10px;\n" + "            text-transform: uppercase;\n"
				+ "            letter-spacing: 1px;\n" + "        }\n"
				+ "        .otp {\n" + "            font-size: 36px;\n" + "            font-weight: bold;\n"
				+ "            color: #ffffff;\n" + "            letter-spacing: 8px;\n" + "            text-shadow: 0 2px 4px rgba(0,0,0,0.3);\n"
				+ "        }\n"
				+ "        .warning {\n" + "            background: #fff3cd;\n" + "            border: 1px solid #ffeaa7;\n"
				+ "            border-radius: 8px;\n" + "            padding: 15px;\n" + "            margin: 20px 0;\n"
				+ "            color: #856404;\n" + "            font-size: 14px;\n" + "        }\n"
				+ "        .footer {\n" + "            background: #f8f9fa;\n" + "            padding: 20px;\n"
				+ "            text-align: center;\n" + "            border-top: 1px solid #e9ecef;\n" + "        }\n"
				+ "        .footer p {\n" + "            margin: 0;\n" + "            font-size: 12px;\n"
				+ "            color: #6c757d;\n" + "        }\n"
				+ "        .logo {\n" + "            font-weight: bold;\n" + "            color: #1e3c72;\n" + "        }\n"
				+ "    </style>\n" + "</head>\n" + "<body>\n"
				+ "    <div class=\"container\">\n" + "        <div class=\"header\">\n"
				+ "            <h1>Password Reset</h1>\n" + "        </div>\n" + "        <div class=\"body\">\n"
				+ "            <div class=\"greeting\">Hello <strong>"+name+"</strong> 👋</div>\n"
				+ "            <div class=\"message\">We received a request to reset your password for your JobPortal account.</div>\n"
				+ "            <div class=\"otp-container\">\n"
				+ "                <div class=\"otp-label\">Your Verification Code</div>\n"
				+ "                <div class=\"otp\">" + otp + "</div>\n"
				+ "            </div>\n"
				+ "            <div class=\"warning\">\n"
				+ "                ⏰ This code will expire in 5 minutes.<br>\n"
				+ "                🔒 If you didn't request this, please ignore this email.\n"
				+ "            </div>\n"
				+ "            <div style=\"margin-top: 30px; color: #666; font-size: 14px;\">\n"
				+ "                Need help? Contact our support team at jobportal.bogdanveremienko@gmail.com\n"
				+ "            </div>\n" + "        </div>\n"
				+ "        <div class=\"footer\">\n" + "            <p>&copy;" + Year.now().getValue()
				+ " <span class=\"logo\">JobPortal</span>. All rights reserved.</p>\n"
				+ "            <p>Secure • Reliable • Professional</p>\n" + "        </div>\n" + "    </div>\n" + "</body>\n"
				+ "</html>";
	}
}
